language: node_js
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
env:
  - BUILD_LEADER_ID=4
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - npm prune
jobs:
  include:
    - stage: release
      node_js: 8
      os: linux
      after_success:
        - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false"
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - npm run semantic-release
